name: C:\Users\Sergei\Anaconda3\envs\othodi3
dependencies:
- backports_abc=0.4=py27_0
- bokeh=0.10.0=py27_0
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- markupsafe=0.23=py27_0
- msvc_runtime=1.0.1=vc9_0
- numpy=1.10.1=py27_0
- pandas=0.17.1=np110py27_0
- pil=1.1.7=py27_0
- pip=7.1.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_2
- pyzmq=15.1.0=py27_0
- requests=2.9.0=py27_0
- setuptools=19.1.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- tornado=4.3=py27_0
- werkzeug=0.11.3=py27_0
- wheel=0.26.0=py27_1
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.4.1
  - dropbox==4.0
  - urllib3==1.14

